export const SET_LOGIN_STATE = 'SET_LOGIN_STATE';
export const LOG_OUT = 'LOG_OUT';
export const OPEN_LOGIN_PORTAL = 'OPEN_LOGIN_PORTAL';
export const CLOSE_LOGIN_PORTAL = 'CLOSE_LOGIN_PORTAL';
export const OPEN_SIGNUP_PORTAL = 'OPEN_SIGNUP_PORTAL';
export const CLOSE_SIGNUP_PORTAL = 'CLOSE_SIGNUP_PORTAL';
export const SET_RECIPE_ID = 'SET_RECIPE_ID';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';